### ISSUE TITLE
Matplotlib backend for cubefit-plot

### ISSUE THREAD

**Issue by nicolaschotard** [snfactory/cubefit#13]
Could the backend selection be exposed in an option of cubefit-plot? When running the code at CC, I had to manually modify the plotting library to make it work by uncommenting the two corresponding lines.

**Comment by kbarbary** [comment]
@cmsaunders Can we just permanently uncomment those lines?

(These lines: https://github.com/snfactory/cubefit/blob/master/cubefit/plotting.py#L8-L9)

**Comment by kbarbary** [comment]
ping

**Comment by cmsaunders** [comment]
Okay, I'm fixing it.

**Comment by kbarbary** [comment]
Fixed in ddfacdf62e2a19cb2c83b9967ada19d0e30f53d9
