### ISSUE TITLE
Error in min_l_bfgs_b()

### ISSUE THREAD

**Issue by nicolaschotard** [snfactory/cubefit#15]
An other type of error if the follwoing one, also encountered for a few SNe, mostly in the R channel. Here is the absolute path to the config file:

/afs/in2p3.fr/group/snovae/snprodJob/00-13/cubefit/SNNGC6801/SNF-0013-CUBEFIT_Rb-NGC6801_config.json

INFO: cubefit started at 2015-09-17 08:04:24
INFO: parameters: mu_wave=0.07 mu_xy=0.001 refitgal=False
INFO: reading config file
INFO: reading 4 data cubes
INFO: setting up PSF and ADR for all 4 epochs
INFO: guessing sky for all 4 epochs
INFO: fitting galaxy to master ref [3]
INFO:         success: 235 iterations, 258 calls, val=298313.72
INFO: fitting position of non-master refs [2]
INFO:         success:  27 iterations,  52 calls, val=192758.18
INFO: fitting galaxy to all refs [2, 3]
INFO:         success:   1 iterations,   3 calls, val=581854.52
INFO:         initial œ<87>¬≤/epoch: [5994968.41, 6753620.45]
INFO:         final   œ<87>¬≤/epoch: [5994968.40, 6753620.45]
INFO: fitting position of all 2 non-refs and SN position
Traceback (most recent call last):
  File "/afs/in2p3.fr/group/snovae/snf/cubefit/bin/cubefit", line 45, in <module>
    master_ref=args.master_ref)
  File "/afs/in2p3.fr/group/snovae/snf/cubefit/lib/python2.7/site-packages/cubefit/main.py", line 283, in main
    snctr, atms_nonrefs)
  File "/afs/in2p3.fr/group/snovae/snf/cubefit/lib/python2.7/site-packages/cubefit/fitting.py", line 557, in fit_position_sky_sn_multi
    _check_result(d['warnflag'], d['task'])
  File "/afs/in2p3.fr/group/snovae/snf/cubefit/lib/python2.7/site-packages/cubefit/fitting.py", line 23, in _check_result
    raise RuntimeError("fmin_l_bfgs_b() exited with warnflag=2: %s" % msg)
RuntimeError: fmin_l_bfgs_b() exited with warnflag=2: ABNORMAL_TERMINATION_IN_LNSRCH

**Comment by kbarbary** [comment]
I can reproduce this. Interestingly, I see different numbers for chisq/epoch in the log output though.

**Comment by kbarbary** [comment]
I tried on Python 2.7 (Anaconda build) and still can't reproduce the log exactly. (iterations and chisq values are still different.)

@nicolaschotard Can you post the versions of numpy, scipy, pyfftw, libfftw3 you're using? Also double check that everything is 64-bit?

**Comment by cmsaunders** [comment]
I did the fit for the R band of SNF20070831-015, which we talked about on
the VC, and I got pretty different results from the ones in the zoo. Here
are the thumbnails (compare to
http://snf.in2p3.fr/history/0726305600322508200013000/):

**Comment by kbarbary** [comment]
@cmsaunders Should we open a separate issue for SNF20070831-005? (It's likely a different problem than this one. 

I don't think your images came through. Try the github web interface rather than email.

**Comment by cmsaunders** [comment]
Sure, I was just thinking it was more evidence of getting different results
on cc versus other machines. (I also forgot this isn't just an email
chain.)

**Comment by kbarbary** [comment]
Yeah I have an automatic label filter in gmail so that I can easily see what things are actually github issues.

**Comment by nicolaschotard** [comment]
Everything is under 64-bit, and here are the version of the codes we are using at CC: 
numpy: 1.7.1
scipy: 0.12.0
pyfftw: 0.9.2
libfftw3: fftw3
from 
In [38]: pyfftw.pyfftw.np.distutils.system_info.get_info('fftw')
Out[38]: 
{'define_macros': [('SCIPY_FFTW3_H', None)],
 'include_dirs': ['/usr/include'],
 'libraries': ['fftw3'],
 'library_dirs': ['/usr/lib64']}

**Comment by nicolaschotard** [comment]
Update. I've made a little change in plan_cubefit to use the real temperature of the exposures instead of the default value of 2 degrees. It seems to be enough to fix this problem for the 5 SNe that had this error. Do you know how these not so big differences in temperature could do that? Anyways, even if I do not have SNe having this error anymore, their fit is sometimes not as good as in DDT, even if it now converges. This is something I need to study in more details. Here is the list of SNe, that you can find on the zoo under http://snf.in2p3.fr/zoo/SNF-0013-CUBEFIT (e.g. http://snf.in2p3.fr/lc/SNF-0013-CUBEFIT,ALLAIRE/SN2005cc): LSQ12hjm, SN2005cc, SNF20060912-004, SNF20080806-002, SNNGC6801.

I also discussed it with Yannick who think that there is also room for improvement in the way the ADR is computed by using some code already wrote for extract_star (libExtractstar).

**Comment by kbarbary** [comment]
To be clear, cubefit is using code from Toolbox for ADR (the contents of `cubefit/extern.py` is mostly a copy-paste from `Toolbox/Astro/Coords.py` and `Toolbox/Atmosphere.py`; "extern" is for "external"). Does libExtractStar use different ADR code?

**Comment by ycopin** [comment]
No, the ADR code is fine, but it's about the effective airmass and parallactic angle to be used. Rather than using plain AIRMASS keyword and recompute parang from HA/DEC + MLA_tilt, you should look at prediction used in `SNFactory:Offline/pySNIFS/lib/libExtractStar.py` `Hyper_PSF3D_PL.predict_adr_params` which includes a the MLA tilt as well as a flexure model.

**Comment by kbarbary** [comment]
Ah I see. I'll have a look.

**Comment by kbarbary** [comment]
The SNNGC6801 story gets stranger. I set up a conda environment as follows:

```
(cubefit-prod)kyle@photon:~/code/cubefit/testset$ conda list
# packages in environment at /home/kyle/.conda/envs/cubefit-prod:
#
fitsio                    0.9.7                     <pip>
matplotlib                1.3.1                np17py27_0  
numpy                     1.7.1                    py27_3  
pyfftw                    0.9.2                     <pip>
python                    2.7.10                        1  
scipy                     0.12.0               np17py27_0  
```

Running cubefit in this environment, SNNGC6801_R actually succeeds!

```
INFO cubefit started at 2015-09-25 11:09:42
INFO parameters: mu_wave=0.07 mu_xy=0.001 refitgal=False
INFO reading config file
INFO reading 4 data cubes
INFO setting up PSF and ADR for all 4 epochs
INFO guessing sky for all 4 epochs
INFO fitting galaxy to master ref [3]
INFO         success: 309 iterations, 335 calls, val=297333.84
INFO fitting position of non-master refs [2]
INFO         success:  31 iterations,  62 calls, val=195608.15
INFO fitting galaxy to all refs [2, 3]
INFO         success:   1 iterations,   3 calls, val=580380.36
INFO         initial χ²/epoch: [5993828.30, 6752282.24]
INFO         final   χ²/epoch: [5993828.29, 6752282.23]
INFO fitting position of all 2 non-refs and SN position
INFO         success:  11 iterations,  61 calls, val=800210.79
INFO writing results to results/SNNGC6801_R.fits
INFO step times:
INFO         0m02s - setup                        
INFO         3m05s - fit galaxy to master ref     
INFO         0m02s - fit positions of other refs  
INFO         0m03s - fit galaxy to all refs       
INFO         0m28s - fit positions of nonrefs & SN
INFO finished at 2015-09-25 11:13:23
INFO took 3m41s
```

So we're seeing at least 3 different behaviors, 2 of which are on environments that are supposedly identical. :cry:

**Comment by cmsaunders** [comment]
I got very similar but not identical results with
python: 2.7.8
fitsio: 0.9.5
numpy: 1.9.1
scipy: 0.14.0
pyfftw: 0.9.2

**Comment by kbarbary** [comment]
Only remaining guess is the specific libfftw3 version. I have 3.3.2.

**Comment by kbarbary** [comment]
This sucks.

**Comment by kbarbary** [comment]
Opened a new issue #18 for potential improvement to ADR code (unrelated to this issue). Remaining problems in this issue:

- the fact that fmin_l_bfgs_b fails at all, ever
- can't repeat results identically between platforms, even when software stack seems identical
- over-sensitivity of results to input temperatures

**Comment by cmsaunders** [comment]
I tried using Nico's command to get my libfftw3
(pyfftw.pyfftw.np.distutils.system_info.get_info('fftw')) and the command
failed, despite using the same version of pyfftw.

**Comment by cmsaunders** [comment]
With Kyle Boone's help I got the command to run, but I just get an empty
dictionary.

**Comment by kbarbary** [comment]
@cmsaunders Me too. (`from numpy.distutils import system_info; system_info('fftw')`). However, that won't tell you the version anyway. Look for `libfftw3*` in `/usr/lib/` or `/usr/lib/x86_64-linux-gnu/` on linux. Not sure where these are on OS X.

**Comment by cmsaunders** [comment]
Ok, I have 3.2.3 (on rivoli)

**Comment by kbarbary** [comment]
All SNe with this error (from Nico):

```
LSQ12dbr/SNF-0013-CUBEFIT2_Rb-LSQ12dbr.err:RuntimeError: fmin_l_bfgs_b() exited with warnflag=2: ABNORMAL_TERMINATION_IN_LNSRCH
PTF10nlg/SNF-0013-CUBEFIT2_Bb-10nlg.err:RuntimeError: fmin_l_bfgs_b() exited with warnflag=2: ABNORMAL_TERMINATION_IN_LNSRCH
SN2005ki/SNF-0013-CUBEFIT2_Bb-2005ki.err:RuntimeError: fmin_l_bfgs_b() exited with warnflag=2: ABNORMAL_TERMINATION_IN_LNSRCH
SN2005ki/SNF-0013-CUBEFIT2_Rb-2005ki.err:RuntimeError: fmin_l_bfgs_b() exited with warnflag=2: ABNORMAL_TERMINATION_IN_LNSRCH
SN2006ac/SNF-0013-CUBEFIT2_Bb-2006ac.err:RuntimeError: fmin_l_bfgs_b() exited with warnflag=2: ABNORMAL_TERMINATION_IN_LNSRCH
SN2011by/SNF-0013-CUBEFIT2_Rb-2011by.err:RuntimeError: fmin_l_bfgs_b() exited with warnflag=2: ABNORMAL_TERMINATION_IN_LNSRCH
SNF20050919-000/SNF-0013-CUBEFIT2_Bb-20050919-000.err:RuntimeError: fmin_l_bfgs_b() exited with warnflag=2: ABNORMAL_TERMINATION_IN_LNSRCH
SNF20051003-003/SNF-0013-CUBEFIT2_Rb-20051003-003.err:RuntimeError: fmin_l_bfgs_b() exited with warnflag=2: ABNORMAL_TERMINATION_IN_LNSRCH
SNF20060624-019/SNF-0013-CUBEFIT2_Rb-20060624-019.err:RuntimeError: fmin_l_bfgs_b() exited with warnflag=2: ABNORMAL_TERMINATION_IN_LNSRCH
SNF20070427-001/SNF-0013-CUBEFIT2_Rb-20070427-001.err:RuntimeError: fmin_l_bfgs_b() exited with warnflag=2: ABNORMAL_TERMINATION_IN_LNSRCH
SNF20080821-000/SNF-0013-CUBEFIT2_Rb-20080821-000.err:RuntimeError: fmin_l_bfgs_b() exited with warnflag=2: ABNORMAL_TERMINATION_IN_LNSRCH
SNF20080918-000/SNF-0013-CUBEFIT2_Rb-20080918-000.err:RuntimeError: fmin_l_bfgs_b() exited with warnflag=2: ABNORMAL_TERMINATION_IN_LNSRCH
SNNGC4424/SNF-0013-CUBEFIT2_Rb-NGC4424.err:RuntimeError: fmin_l_bfgs_b() exited with warnflag=2: ABNORMAL_TERMINATION_IN_LNSRCH
SNNGC6801/SNF-0013-CUBEFIT2_Bb-NGC6801.err:RuntimeError: fmin_l_bfgs_b() exited with warnflag=2: ABNORMAL_TERMINATION_IN_LNSRCH
SNNGC6801/SNF-0013-CUBEFIT2_Rb-NGC6801.err:RuntimeError: fmin_l_bfgs_b() exited with warnflag=2: ABNORMAL_TERMINATION_IN_LNSRCH
```

**Comment by kbarbary** [comment]
I ran all these SNe locally with the latest master (contains only small changes from v0.2.1), and all of them succeeded except for SN2005ki B channel. I'm now going to try v0.2.1 locally on at least a few.

I noticed that many (but not all) of these cases have no apparent galaxy.

Finally, I also noticed that in the final fit step, we're not passing a `factr` argument to `fmin_l_bfgs_b`. It's possible that specifying a larger factor that the default will make this more stable.

**Comment by kbarbary** [comment]
I suspected that the instability in `fmin_l_bfgs_b` in the last fitting step was due to using a finite-differences gradient calculation.

I've now implemented an analytic gradient function for this step. Hopefully this should fix these problems, but the only way to tell might be to run in production.

There's still the matter of non-reproducible results depending on platform, but I don't know what to do about that.

**Comment by nicolaschotard** [comment]
I will run a third production as soon as you think w ehave a stable version (v0.3 maybe?). Please let me know if you are still makinng changes before I start.

**Comment by kbarbary** [comment]
Just tagged v0.3.0. Go for it.

**Comment by nicolaschotard** [comment]
Hi guys,

I’ve run a new full cubefit pruduction using version v0.3.0, Results looks good, and all errors disappeared! Good job! You can find it here <http://snf.in2p3.fr/prod/SNF-0013-CUBEFIT3a/> and there <http://snf.in2p3.fr/zoo/SNF-0013-CUBEFIT3a/>  We can discuss it during next VC.

**Comment by kbarbary** [comment]
Yay! :fireworks:
