### ISSUE TITLE
Extra iteration on final ref fits

### ISSUE THREAD

**Issue by nicolaschotard** [snfactory/cubefit#17]
I've run 3 new jobs using the 3 other references of SNF20070831-15 (at cc). You can find all the results here: http://snf.in2p3.fr/lc/SNF-0013-CUBEFIT,ALLAIRE/SNF20070831-015. They do not seem to be much better when using one of the 2 first reference (not misaligned) as master reference.

And here are the plots from cubefit for the B channel (#master_ref):

http://snf.in2p3.fr/history/0726305600342508200013002/  /#16
http://snf.in2p3.fr/history/0726305600342508290013003/  /#17
http://snf.in2p3.fr/history/0726305600342508200013001/  /#18
http://snf.in2p3.fr/history/0726305600342508200013000/  /#19

You can get the R channel by changing the 4 by a 2 in the middle of the process name (342->322). 

ps: there is a bug on the zoo that I'm trying to fix. Triangles do not point to the right spectrum and cube (left and right clicks).

**Comment by kbarbary** [comment]
Thanks Nico; good to have an issue open to track this.

**Comment by cmsaunders** [comment]
I think I resolved this issue: comparing my fit for this SN and the cc versions, I ended up looking at the config file that I was using (this had been converted from a ddt include file) with the cc version explicitly written for cubefit. It turns out the signs on the xcenter and ycenter parameters are switched! I tested the cc version myself and got results that look like Nico's:
![70831-015_cc_timeseries](https://cloud.githubusercontent.com/assets/5316930/10113135/33727c2a-6396-11e5-9394-d12999f09aaa.png)

When I use the config file with the flipped positions, the results look better (though still not great):
![70831-015_test_timeseries](https://cloud.githubusercontent.com/assets/5316930/10113148/6ebdc0c8-6396-11e5-858b-8ba7835cac62.png)

**Comment by kbarbary** [comment]
This is reassuring! The fit is pretty good: only 5% residuals. They could probably be improved. In cases like this, we could probably use another iteration of fitting position and model on the references. The initial model (step 1) doesn't capture all the references very well, so the position fit of non-master references (step 2) is not very good.

So, is there a sign error in plan_cubefit???

**Comment by kbarbary** [comment]
Also: sweet github avatar. :+1:

**Comment by cmsaunders** [comment]
Thanks, I finally set it up!
I also tried using one of the other (not offset) final refs as the master and got only marginally better results (slightly better chi-squared and thumbnails), though I think the you see less of the galaxy in the residuals.
![70831-015_alt_timeseries](https://cloud.githubusercontent.com/assets/5316930/10114622/eca2c238-63a8-11e5-9e02-267891317cea.png)

**Comment by nicolaschotard** [comment]
I see. The positions "xcenter" and "ycenter" in plan_cubefit are the same as what we had in plan_ddt. But the definition actually changed between DDT and cubefit. DDT needed the position of the SN with respect to the center of the MLA, which is what I give in plan_cubefit as well, whereas cubefit wants the position of the MLA center with respect to the SN position. The sign error comes this misunderstanding. I will fix that in plan_cubefit and let you guys know when I will get the new results.

**Comment by ycopin** [comment]
IMHO, the DDT definition seems more logical...

**Comment by kbarbary** [comment]
Neither are very satisfactory. But the cubefit definition is more like a
typical WCS solution, which gives the position of the data with respect to
some fixed reference frame. In the case of cubefit the "fixed reference
frame" is the SN position.

**Comment by nicolaschotard** [comment]
I've re-run the jobs using the correct inpunts, and it does look much better (See the prod called CUBEFITinva): http://snf.in2p3.fr/lc/SNF-0013-CUBEFIT,ALLAIRE/SNF20070831-015/

**Comment by kbarbary** [comment]
Still to do:  In cases like this, we could probably use another iteration of fitting position and model on the references. The initial model (step 1) doesn't capture all the references very well, so the position fit of non-master references (step 2) is not very good.

**Comment by kbarbary** [comment]
I looked into this SN a bit, and the reference residuals look better with current master (should be the same as the last production). I tried adding an iteration, just for fun, but it doesn't change anything. So I'm closing this.
