### ISSUE TITLE
Use airmass and parallactic angle as in libExtractStar.py

### ISSUE THREAD

**Issue by kbarbary** [snfactory/cubefit#18]
Yannick says:

Rather than using plain AIRMASS keyword and recompute parang from HA/DEC + MLA_tilt, you should look at prediction used in `SNFactory:Offline/pySNIFS/lib/libExtractStar.py`: `Hyper_PSF3D_PL.predict_adr_params` which includes the MLA tilt as well as a flexure model.

**Comment by kbarbary** [comment]
@ycopin If I understand correctly, it looks like `Hyper_PSF3D_PL.predict_adr_params()` makes a channel-dependent correction to `delta` (= tan(arccos(1/airmass))) and `theta` (= parallactic angle), where the parallactic angle and airmass is take from the image header.

Two questions:

1. In cubefit, we calculate the parallactic angle from airmass, ha, dec, mla_tilt and the latitude. Should we switch to using the value in the header rather than calculating it? If so, is it also in the DB? (I'd rather be consistent about using DB values vs header values everywhere.)

2. In cubefit, once we have the parallactic angle, we calculate ADR using
  ```
  ADR(cfg["pressures"][i], cfg["temperatures"][i], lref=REFWAVE,
      airmass=cfg["airmasses"][i], theta=pa)
  ```
  where `pa` is the parallactic angle and the `ADR` class is from `Toolbox.Atmosphere`. I can see how the corrected `theta` value would be used, but how does the corrected `delta` value come in?

**Comment by ycopin** [comment]
1. The DB/header values for airmass and parangle are "naive" geometric values, not including 2nd-order effects such as MLA rotation, mechanical flexures or finite-exposure corrections. While good to 1st-order, they should be replaced by `Hyper_PSF3D_PL.predict_adr_params()` values for higher-accuracy. These values have been trained on faint-std star exposures, and are used as priors for SNe. 

2. You can instantiate `ADR` directly from predicted delta and theta, e.g. from `extract_star`:

```
        delta, theta = libES.Hyper_PSF3D_PL.predict_adr_params(inhdr)
        adr = TA.ADR(pressure, temp, lref=lmid, delta=delta, theta=theta)
```

The pb is that the ADR parameter training has been performed using the "new" power-law PSF, while the PSF prediction you use from gs-psf still uses the "old" polynomial PSF, but I don't think it would make a lot of difference. One thing you could investigate is the usage of the other `libES` predictors, e.g. `Hyper_PSF3D_PL.predict_alpha_coeffs()` from GS-estimated seeing.

**Comment by kbarbary** [comment]
Thanks, this seems clear.

A different issue: are the "new" power-law PSF parameters in the DB in a way that can be passed to cubefit? (It may be that part of the DDT code did this, but it has been a long time since I looked at that code...)

**Comment by kbarbary** [comment]
So we should be using `parangle` from the DB (rather than using [`cubefit.paralactic_angle()`](https://github.com/snfactory/cubefit/blob/master/cubefit/adr.py#L9-L52)) and feed it to `Hyper_PSF3D_PL.predict_adr_params()` to it.

@nicolaschotard Can we modify plan_cubefit to write an array of `parangle` for each exposure to the configuration file?

**Comment by ycopin** [comment]
No, maybe I was not clear: DB and header values are supposed to be the same. Instead, you should use the header values (I don't see the point of extracting them explicitly from DB), and feed them to `Hyper_PSF3D_PL.predict_adr_params()` to retrieve the expected values.

**Comment by kbarbary** [comment]
Got it. My conclusion was not about whether to use the DB or header value of `parangle` (which I understand should be the same). Rather, it was about whether to use a precomputed value of `parangle` (from either the DB or header) instead of recalculating it in cubefit.

**Comment by ycopin** [comment]
I don't think a pipeline plan is the right place to perform any "elaborate" scientific computations: its role should be restricted to selecting appropriate data, launch computations with proper high-level parameters and finally store back the results.  On the other hand, I don't think one should save in the DB the effective (model-dependent) ADR parameters in place of the geometric values currently stored.  So I guess the best place to compute these values is in individual building blocks (extract_star, cubefit), using common libraries if possible to ensure consistency.

**Comment by kbarbary** [comment]
Sounds like we agree.

**Comment by kbarbary** [comment]
Done. See https://github.com/snfactory/cubefit/blob/master/cubefit/main.py#L174-L178 for implementation.

**Comment by kbarbary** [comment]
@nicolaschotard In case you didn't follow this discussion closely, we no longer need `parang` added to the config file in plan_cubefit. It is fine as is.
