### ISSUE TITLE
Be consistent in using header values or DB values

### ISSUE THREAD

**Issue by kbarbary** [snfactory/cubefit#21]
With the implementation of #18 we are now using a few values from FITS headers (airmass, parang) and values from the DB (passed via a config file). We should either use all values from the headers or all values from the DB. It doesn't matter which, but it makes sense to be consistent.

**Comment by ycopin** [comment]
I would consistently favour header values.

**Comment by kbarbary** [comment]
Using header values where possible will let us make the config file *much* simpler, so that sounds good to me. I'll implement this.
