### ISSUE TITLE
Numeric instability in fit_galaxy_sky_multi()

### ISSUE THREAD

**Issue by kbarbary** [snfactory/cubefit#8]
I've discovered a problem with the second galaxy fitting step (in which all the final refs are used to constrain the galaxy model, and the sky for each is varied in the process). I noticed this because the code worked on PTF09fox when `SCALE_FACTOR = 10**17` but failed when `SCALE_FACTOR = 1.e17` (they're subtly different; it's a matter of exact integer representation and the lack of exact floating point representation).

The error is in the form of an "ABNORMAL_TERMINATION_IN_LNSRCH" warning flag in `fmin_l_bfgs_b()`. I'm not sure what the cause is, but I did realize that our gradient function is not exactly right. The gradient function assumes that the sky is held constant (and it is in `fit_galaxy()`). However, in `fit_galaxy_sky_multi()` we recalculate the sky in each iteration. Qualitatively, increasing any given model pixel will result in a lower sky estimate. Since the chisq is `~ (data - model - sky)^2` we need to take this into account in the gradient (the gradient will be lower than calculated).

I did some work understanding and reworking the `docs/gradient.tex` file in order to work out the correct formula. That document is still under construction though.

**Comment by kbarbary** [comment]
Update: even with the fix in the gradient function, I'm still getting this error in the red channel of PTF09fox. Will add a unit test checking the gradient function.

**Comment by kbarbary** [comment]
Update: I now fixed the gradient calculation and added a test to confirm that it works. (...in the chisq part of the gradient at least; I haven't yet tested that the regularization penalty gradient is correct!)

However, I still get a failure in PTF09Fox_R with `mu_wave=0.07, mu_xy=0.001` in `fit_galaxy_sky_multi()`.

With the new default parameter values `mu_wave=5e-4, mu_xy=1e-5`, it gets past `fit_galaxy_sky_multi()` after about 30 minutes, 534 iterations and 1540 function calls. But then it fails in the last step `fit_position_sky_sn_multi()` with the same message from `fmin_l_bfgs_b()`.

Next, I'm going to write tests for the regularization penalty gradient and the gradient in the last step.

**Comment by ycopin** [comment]
You should probably move to a better more robust Minuit-based fitter... As for the verification of gradients, you can use `scipy.optimize.approx_fprime` for scalar function, or `ToolBox.Optimizer.approx_deriv`.

**Comment by kbarbary** [comment]
I've never passed Minuit a gradient function; can it accept one? Is it known to handle large parameter optimizations like the galaxy fit here (~1 million parameters)? We were using L-BFGS-B because we thought it was good for this, but I would be happy to be told otherwise.

For the position fit step with only ~30 parameters, I agree we should try Minuit.

I totally forgot about the existence of `approx_fprime`! Unfortunately, that is the relatively easy part...

**Comment by kbarbary** [comment]
This is hopefully resolved. The gradient tests all pass at least.
